# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "assets", :force => true do |t|
    t.column "assetowner_id",   :integer
    t.column "assetowner_type", :string
    t.column "title",           :string
    t.column "slug",            :string
    t.column "meta",            :text
    t.column "filename",        :string
    t.column "mimetype",        :string
    t.column "notes",           :text
    t.column "is_published",    :boolean,  :default => true
    t.column "published_on",    :datetime
    t.column "position",        :integer,  :default => 0
    t.column "type",            :string
    t.column "created_on",      :datetime
    t.column "updated_on",      :datetime
  end

  add_index "assets", ["assetowner_id", "assetowner_type"], :name => "index_assets_on_assetowner_id_and_assetowner_type"

  create_table "comments", :force => true do |t|
    t.column "user_id",          :integer
    t.column "commentable_id",   :integer
    t.column "commentable_type", :string
    t.column "body",             :text
    t.column "author",           :string
    t.column "url",              :string
    t.column "email",            :string
    t.column "ip_address",       :string
    t.column "user_agent",       :string
    t.column "http_referer",     :string
    t.column "is_spam",          :boolean,  :default => true
    t.column "created_on",       :datetime
    t.column "updated_on",       :datetime
  end

  add_index "comments", ["commentable_id", "commentable_type"], :name => "index_comments_on_commentable_id_and_commentable_type"
  add_index "comments", ["user_id"], :name => "index_comments_on_user_id"

  create_table "contents", :force => true do |t|
    t.column "title",      :string
    t.column "slug",       :string
    t.column "body",       :text
    t.column "type",       :string
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "contents", ["slug", "type"], :name => "index_contents_on_slug_and_type"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"

  create_table "site_config", :force => true do |t|
    t.column "key",   :string,                 :null => false
    t.column "value", :text,   :default => ""
  end

  add_index "site_config", ["key"], :name => "index_site_config_on_key"

  create_table "storylines", :force => true do |t|
    t.column "title",      :string
    t.column "slug",       :string
    t.column "notes",      :text
    t.column "position",   :integer,  :default => 0
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "salt",                      :string,   :limit => 40
    t.column "crypted_password",          :string,   :limit => 40
    t.column "display_name",              :string
    t.column "email",                     :string
    t.column "is_publisher",              :boolean,                :default => false
    t.column "created_on",                :datetime
    t.column "updated_on",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

end
